# Generated by Django 3.1 on 2020-08-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200723_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pname',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
