# Generated by Django 3.1 on 2020-08-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_pname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
