# Generated by Django 3.1 on 2020-08-27 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200809_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pname',
        ),
    ]
