# Generated by Django 3.1 on 2020-08-31 05:37

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200831_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default=django.contrib.auth.models.User, editable=False, max_length=20),
        ),
    ]
